name: New model PR CI

on:
  pull_request:

jobs:
  check_for_new_model:
      # 1st cond: forked repo. --> triggered (even if it is team member, and approve and run won't be there --> always run)
      # 2nd cond: if there is comment with matched string --> triggered
      if: contains(github.event.pull_request.labels.*.name, 'run-slow')
      runs-on: ubuntu-22.04
      name: Check if PR is a new model PR
      steps:
        - name: Check if there is new model
          run: |
            echo "Hello"
            echo "${{ github.event.comment.body }}"
            echo "${{ github.event.pull_request.head.repo.full_name }}"
            echo "${{ github.repository }}"
            echo "${{ github.event_name }}"
            echo "${{ github.actor }}"
            echo ${{ github.event.comment.author_association }}
            echo ${{ github.event.pull_request.author_association }}