name: New model PR CI

on:
  pull_request:
  issue_comment:
    types: [created]

jobs:
  check_for_new_model:
      # 1st cond: forked repo. --> triggered
      # 2nd cond: if there is comment with matched string --> triggered
      if: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) || github.event.comment.body == 'bonbon' }}
      runs-on: ubuntu-22.04
      name: Check if PR is a new model PR
      steps:
        - name: Check if there is new model
          run: |
            echo "Hello"
            echo "${{ github.event.comment.body }}"
            echo "${{ github.event.pull_request.head.repo.full_name }}"
            echo "${{ github.repository }}"
            echo "${{ github.event_name }}"
            echo "${{ github.actor }}"